# Generated by Django 6.0.5 on 2026-06-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('gatherings', 'Gatherings'), ('workshops', 'Workshops'), ('showcases', 'Showcases')], default='cat', max_length=20),
            preserve_default=False,
        ),
    ]
