# Generated by Django 6.0.5 on 2026-06-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gja', '0002_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/')),
                ('category', models.CharField(choices=[('about', 'About'), ('member', 'Member'), ('leadership', 'Leadership')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
