# Generated by Django 6.0.5 on 2026-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gja', '0003_homeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('member', 'Member'), ('leadership', 'Leadership')], max_length=20),
        ),
    ]
